---
env:
  - GO111MODULE=on

env_files:
  gitlab_token: ~/nope
  gitea_token: ~/nope

before:
  hooks:
    - go mod tidy
    - ./scripts/completions.sh
    - ./scripts/manpages.sh

snapshot:
  name_template: '{{ incpatch .Version }}-next'

builds:
  - env:
      - CGO_ENABLED=0
    goos:
      - linux
      - darwin
      - windows
    goarch:
      - "386"
      - amd64
      - arm
      - arm64
    goarm:
      - "7"
    mod_timestamp: '{{ .CommitTimestamp }}'
    flags:
      - -trimpath
    ldflags:
      - -s -w -X main.version={{.Version}} -X main.commit={{.Commit}} -X main.date={{ .CommitDate
        }} -X main.builtBy=goreleaser
    main: ./cmd/finas/

universal_binaries:
  - replace: false

checksum:
  name_template: 'checksums.txt'

changelog:
  sort: asc
  use: github
  filters:
    exclude:
      - '^test:'
      - '^chore'
      - 'merge conflict'
      - Merge pull request
      - Merge remote-tracking branch
      - Merge branch
      - go mod tidy
  groups:
    - title: Dependency updates
      regexp: "^.*feat\\(deps\\)*:+.*$"
      order: 300
    - title: 'New Features'
      regexp: "^.*feat[(\\w)]*:+.*$"
      order: 100
    - title: 'Bug fixes'
      regexp: "^.*fix[(\\w)]*:+.*$"
      order: 200
    - title: 'Documentation updates'
      regexp: "^.*docs[(\\w)]*:+.*$"
      order: 400
    - title: Other work
      order: 9999

archives:
  - name_template: >-
      {{ .ProjectName }}_
      {{- title .Os }}_
      {{- if eq .Arch "amd64" }}x86_64
      {{- else if eq .Arch "386" }}i386
      {{- else }}{{ .Arch }}{{ end }}
    format_overrides:
      - goos: windows
        format: zip
    files:
      - README.md
      - LICENSE
      - completions/*
      - manpages/*

nfpms:
  - file_name_template: '{{ .ConventionalFileName }}'
    id: packages
    homepage: https://github.com/toozej/finas
    description: |-
      Golang starter template
    maintainer: toozej
    license: GPLv3
    vendor: finas
    bindir: /usr/bin
    section: utils
    contents:
      - src: ./completions/finas.bash
        dst: /usr/share/bash-completion/completions/finas
        file_info:
          mode: 0644
      - src: ./completions/finas.fish
        dst: /usr/share/fish/completions/finas.fish
        file_info:
          mode: 0644
      - src: ./completions/finas.zsh
        dst: /usr/share/zsh/vendor-completions/_finas
        file_info:
          mode: 0644
      - src: ./manpages/finas.1.gz
        dst: /usr/share/man/man1/finas.1.gz
        file_info:
          mode: 0644
      - src: ./LICENSE
        dst: /usr/share/doc/finas/copyright
        file_info:
          mode: 0644
    formats:
      - apk
      - deb
      - rpm
    dependencies:
      - git
    recommends:
      - golang
    deb:
      lintian_overrides:
        - statically-linked-binary
        - changelog-file-missing-in-native-package

sboms:
  - artifacts: archive

signs:
  - cmd: cosign
    stdin: '{{ .Env.COSIGN_PASSWORD }}'
    output: true
    args:
      - 'sign-blob'
      - '--key=finas.key'
      - '--output-signature=${signature}'
      - '${artifact}'
    artifacts: all

milestones:
  - close: true

release:
  footer: |
    **Full Changelog**: https://github.com/toozej/finas/compare/{{ .PreviousTag }}...{{ .Tag }}
