---
name: ci

on:
  pull_request:
  workflow_dispatch:
  push:
  schedule:
    - cron: "0 1 * * 1"

jobs:
  checks:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - uses: actions/setup-go@v4
        with:
          go-version: '^1.21'
          check-latest: true
      - name: Run pre-commit
        run: |
          pip install pre-commit
          make pre-commit
