---
name: release

on:
  workflow_run:
    workflows: [security]
    types: [completed]
    branches: [master]
    tags: ["*"]

permissions:
  contents: write
  packages: write

jobs:
  goreleaser:
    runs-on: ubuntu-latest
    if: github.event_name == 'push' && contains(github.ref, 'refs/tags/')
    steps:
      - name: Checkout
        uses: actions/checkout@v3
        with:
          fetch-depth: 0
      - name: Fetch all tags
        run: git fetch --force --tags
      - name: Set up Go
        uses: actions/setup-go@v4
        with:
          go-version: '^1.21'
          check-latest: true
      - name: Grab Cosign private key
        run: |
          echo "${COSIGN_PRIVATE_KEY}" > ./gonote.key
          chmod 0600 ./gonote.key
        env:
          COSIGN_PRIVATE_KEY: ${{ secrets.COSIGN_PRIVATE_KEY }}
      - name: Login to DockerHub
        uses: docker/login-action@v2
        # https://docs.docker.com/docker-hub/access-tokens/
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}
      - name: Login to GitHub Container Registry
        uses: docker/login-action@v2
        # https://docs.github.com/en/packages/working-with-a-github-packages-registry/working-with-the-container-registry
        with:
          registry: ghcr.io
          username: ${{ github.repository_owner }}
          password: ${{ secrets.GH_GHCR_TOKEN }}
      - name: Login to Quay Container Registry
        uses: docker/login-action@v2
        # https://github.com/marketplace/actions/push-to-registry#examples
        with:
          registry: quay.io
          username: ${{ secrets.QUAY_USERNAME }}
          password: ${{ secrets.QUAY_TOKEN }}
      - name: Run GoReleaser
        uses: goreleaser/goreleaser-action@v4 # nosemgrep: yaml.github-actions.security.third-party-action-not-pinned-to-commit-sha.third-party-action-not-pinned-to-commit-sha
        with:
          distribution: goreleaser
          version: latest
          args: release --rm-dist
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
      - name: Clean up Cosign private key
        run: shred -u ./gonote.key
  
  verify_signed_docker_images:
    runs-on: ubuntu-latest
    if: github.event_name == 'push' && contains(github.ref, 'refs/tags/')
    permissions: {}
    strategy:
      matrix:
        registry: ['', 'ghcr.io/', 'quay.io/']
        tag: ['latest', '-arm64', '-amd64']
    steps:
      - name: Install Cosign
        uses: sigstore/cosign-installer@main
      - name: Get public cosign key for dinnerclub project from GitHub
        run: |
          curl --silent https://raw.githubusercontent.com/toozej/gonote/master/gonote.pub -O
      - name: Verify signatures of Docker images
        run: |
          cosign verify --key gonote.pub \
            ${{ matrix.registry }}toozej/gonote:${{ matrix.tag }}

  verify_signed_binaries:
    runs-on: ubuntu-latest
    if: github.event_name == 'push' && contains(github.ref, 'refs/tags/')
    permissions: {}
    strategy:
      matrix:
        platform: ['darwin', 'linux', 'windows']
        arch: ['all', 'amd64_v1', 'arm64', 'arm_7', '386']
        extension: ['', '.exe']
    steps:
      - name: Install Cosign
        uses: sigstore/cosign-installer@main # nosemgrep: yaml.github-actions.security.third-party-action-not-pinned-to-commit-sha.third-party-action-not-pinned-to-commit-sha
      - name: Get public cosign key
        run: |
          curl --silent https://raw.githubusercontent.com/toozej/gonote/master/gonote.pub -O
      - name: Verify signatures of binaries
        run: |
          FILE=./dist/gonote_${{ matrix.platform }}_${{ matrix.arch }}/gonote${{ matrix.extension }}
          if test -f "${FILE}"; then
            echo "verifying binary: ${FILE}"
            cosign verify --key gonote.pub --signature "${FILE}.sig" "${FILE}"
          else
            echo "skipping verifying non-existant binary: ${FILE}"
          fi

  verify_signed_archives:
    runs-on: ubuntu-latest
    if: github.event_name == 'push' && contains(github.ref, 'refs/tags/')
    permissions: {}
    strategy:
      matrix:
        platform: ['Darwin', 'Linux', 'Windows']
        arch: ['all', 'arm64', 'armv7', 'i386', 'x86_64']
        extension: ['tar.gz', 'zip']
    steps:
      - name: Install Cosign
        uses: sigstore/cosign-installer@main # nosemgrep: yaml.github-actions.security.third-party-action-not-pinned-to-commit-sha.third-party-action-not-pinned-to-commit-sha
      - name: Get public cosign key
        run: |
          curl --silent https://raw.githubusercontent.com/toozej/gonote/master/gonote.pub -O
      - name: Verify signatures of archives
        run: |
          FILE=./dist/gonote_${{ matrix.platform }}_${{ matrix.arch }}.${{ matrix.extension }}
          if test -f "${FILE}"; then
            echo "verifying archive: ${FILE}"
            cosign verify --key gonote.pub --signature "${FILE}.sig" "${FILE}"
          else
            echo "skipping verifying non-existant archive: ${FILE}"
          fi
